# Numpy is the powerful library for mathematical operations

In [4]:
import numpy as np 

 # Creating an array

In [2]:
a=np.array([1,2,3,4,5]) 

print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


 # Shape (Attribute)

In [4]:
a.shape  # 1D array(linear array)

(5,)

In [5]:
b=np.array([[1],[2],[3],[4],[5]]) # array has 5 rows and 1 column and it is a kind of 2D array.
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [6]:
# if you want to access 1 of b array
print(b[0][0])

1


In [7]:
s=np.array([[1,2,3],[4,5,6]])  # 2D  array
print(s)
print(s.shape)
print(type(s))

[[1 2 3]
 [4 5 6]]
(2, 3)
<class 'numpy.ndarray'>


In [8]:
print(s[1][1])

5


# Creating zeros array


In [9]:
z=np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Creating ones array

In [10]:
o=np.ones((4,5))
print(o)
print(type(o))
print(o.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>
(4, 5)


# Array of some constant (Full function)

In [11]:

f=np.full((2,3),5)  # 2 and 3 are r and c and 5 is constant 
print(f)
constantarray=np.full((2,3),6)
print(constantarray)

[[5 5 5]
 [5 5 5]]
[[6 6 6]
 [6 6 6]]


# Identity Matrix (eye function)

In [12]:
i=np.eye(4) # square matrix
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Random Matrix

In [5]:
r=np.random.random((2,3))
print(r)

[[0.80328739 0.74107939 0.16975384]
 [0.62728258 0.58141541 0.08854172]]


In [6]:
print(r[ : ,1]) # here we need the whole row so no ending value and no starting value and column is fixed that is 1.

[0.74107939 0.58141541]


In [9]:
print(r[ 0:1 , 1])

[0.74107939]


# How to update values in random matrix

In [10]:
r[1, 1:]=1

In [16]:
r

array([[0.21643019, 0.92408871, 0.41944845],
       [0.75886947, 1.        , 1.        ]])

# Set some rows and columns with any values

In [13]:
z=np.zeros((3,3))
print(z)
z[1,:]=5
z[:,-1]=7
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


# Datatypes

In [15]:
print(z.dtype)

float64


# Change the datatype

In [20]:
z=np.zeros((3,3), dtype=np.int64)
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [21]:
print(z.dtype)

int64


# Mathematical Operations

# +,-,*,/

In [26]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
print(a1+a2)
print(np.add(a1,a2))
print(np.subtract(a1,a2))
print(np.divide(a1,a2))
print(np.multiply(a1,a2))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 5 12]
 [21 32]]


In [27]:
print(np.sqrt(a1))

[[1.         1.41421356]
 [1.73205081 2.        ]]


# Dot product

In [29]:
print(a1)
print(a2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [30]:
print(np.dot(a1,a2))

[[19 22]
 [43 50]]


In [31]:
print(a1.dot(a2))

[[19 22]
 [43 50]]


# Multiplication of Vector

In [32]:
# answer will be scalar 
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a.dot(b))

30


In [34]:
print(np.sum(a))

10


In [38]:
x=np.array([[1,2],[3,4]])
print(x)
print(np.sum(x,axis=0)) # column wise sum

[[1 2]
 [3 4]]
[4 6]


# Row wise sum

In [40]:
x=np.array([[1,2],[3,4]])
print(x)
print(np.sum(x,axis=1))  

[[1 2]
 [3 4]]
[3 7]


# Stack Function

In [42]:
print(a)
b=b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


# Combining arrays using stack

In [48]:
print(a)
print(b)
c=np.stack((a,b),axis=1)
print(c)

[1 2 3 4]
[ 1  4  9 16]
[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


# Reshape a numpy array

In [49]:
c

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [54]:
c=c.reshape((2,4))
print(c) # when you dont know that how you want to reshape then write -1 instead r and c number but for only one of them.

[[ 1  1  2  4]
 [ 3  9  4 16]]
