In [ ]:

import numpy as np
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# What if you want to start your array from 5?

In [ ]:
a=np.arange(10)+5
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# shuffle

In [ ]:

import random
np.random.shuffle(a)
print(a)

[11 14  7  9 13  6  5 12  8 10]


# rand function (generate random values in a given shape)

In [ ]:
np.random.rand(2,3)

array([[0.42064247, 0.24358813, 0.67808197],
       [0.78771757, 0.81758329, 0.88742556]])

# randn funciton ( return a sample from the "standard normal distribution")


In [ ]:
np.random.randn(2,3) # values from std normal distribution

array([[-0.08463573, -0.04697859, -0.62270862],
       [ 0.37697795,  0.60959663,  0.91678339]])

# randint function ( returns numbers within the given range )

In [ ]:
np.random.randint(5,10,3)

array([8, 8, 9])

# choice function

In [ ]:
np.random.choice([1,2,3,4,43]) # randomly choose any one element from array

4